In [2]:
import numpy as np

In [3]:
L=[1,2,3]

In [4]:
A=np.array([1,2,3])

In [5]:
2*L


[1, 2, 3, 1, 2, 3]

In [6]:
2*A

array([2, 4, 6])

In [7]:
A+[8]

array([ 9, 10, 11])

In [8]:
L+[8]

[1, 2, 3, 8]

In [27]:
a1=np.array([1,2,3])
a2=np.array([1,2,3])

dot =0
for e,f in zip(a1,a2):
    dot+=e*f

In [13]:
dot

array([5])

In [28]:
a1*a2

array([1, 4, 9])

In [15]:
zip(a1,a2)

In [19]:
for e in zip(a1,a2):
   print(e) 

(1, array([1]))
(2, array([2]))


In [24]:
np.dot(a1,a2)

5

In [25]:
a1.dot(a2)

5

In [29]:
from datetime import datetime

In [30]:
a=np.random.rand(100)

In [31]:
a

array([ 0.62462002,  0.82183148,  0.82065749,  0.84324145,  0.46115092,
        0.80724951,  0.03621115,  0.587949  ,  0.53949481,  0.46529615,
        0.47388174,  0.99077687,  0.67349221,  0.55881992,  0.50925809,
        0.08263099,  0.53369495,  0.94300728,  0.59276538,  0.1588376 ,
        0.37121077,  0.30106621,  0.53533025,  0.70137934,  0.02181612,
        0.07247237,  0.55339346,  0.71790766,  0.96555539,  0.40206203,
        0.65864814,  0.54284343,  0.29093096,  0.40854951,  0.4169673 ,
        0.50803551,  0.48686762,  0.20254691,  0.23937119,  0.31819038,
        0.08853011,  0.889638  ,  0.95513905,  0.99782341,  0.20468386,
        0.47245907,  0.60876667,  0.69172667,  0.10841592,  0.86271325,
        0.77270749,  0.06026155,  0.82468785,  0.0316432 ,  0.31830692,
        0.76033252,  0.97276829,  0.13883368,  0.42034745,  0.73344278,
        0.80006718,  0.43906057,  0.7227872 ,  0.82524071,  0.84929551,
        0.14396948,  0.16413883,  0.12295678,  0.89505075,  0.93

In [32]:
a1=np.random.randn(100)
a1

array([ 1.08835028, -0.77436753,  0.62938797, -1.05491719,  1.15654794,
       -0.36862048, -0.93398946,  0.04743692,  2.30692902, -0.14008587,
        0.95676842, -1.3848866 , -0.25580184, -0.17075583, -1.63559348,
       -2.39876823,  0.46139142,  0.75892682,  1.87532746, -1.734629  ,
       -2.00167429,  1.15935827,  0.76368575, -1.63986163, -0.16477056,
       -0.64587221,  0.76350002, -1.95182791, -0.02129185, -0.70513405,
        0.79410368,  0.34302942,  0.52073638, -0.5646127 ,  2.32694322,
       -1.0376482 ,  1.21150406, -0.23459266, -1.66068184, -0.01630235,
        0.25428566, -0.1484186 ,  0.55915057, -0.98683832, -0.6043465 ,
        1.18695383, -0.35764721,  0.68996896, -3.68530132,  1.20757931,
       -1.00306543, -1.70220012, -0.30255187,  1.27634811,  0.58213837,
       -3.06593412,  0.98292745,  2.12594873,  0.6331637 , -1.66527579,
        0.93918362, -0.55300486, -0.96966702, -0.71441987, -1.41642117,
       -0.42235674,  0.33242868,  1.93637298, -0.93897207,  0.68

In [33]:
a2=np.random.randn(100,10,10)
a2

array([[[ 0.82158367,  1.0986065 , -0.0270754 , ...,  0.17492858,
          0.74325518, -0.23203472],
        [-0.64429816,  1.54697552, -0.16599174, ...,  0.80908507,
         -0.94834048, -1.22408363],
        [-0.64022477,  0.1448513 ,  0.42934295, ...,  0.19541829,
         -1.36404895, -1.11434532],
        ..., 
        [ 1.74070243, -0.03631815, -1.96182201, ...,  0.47140735,
          0.38318417,  0.58801976],
        [-0.59783051,  0.33388016, -2.47326817, ..., -1.00769956,
         -1.73145952, -1.5729772 ],
        [ 0.59688911, -0.77437808,  0.71827261, ...,  0.12275211,
          0.82844154,  1.20588042]],

       [[-1.46019608,  0.16388694,  0.28772262, ...,  1.70199313,
         -0.91504579,  1.79278648],
        [ 1.49922457, -2.08075158,  0.26987528, ...,  0.59001792,
         -1.57912491,  1.44315888],
        [-1.73937967, -0.56989934,  1.20133017, ..., -0.01540951,
          1.75108615, -0.24482392],
        ..., 
        [ 0.18394327, -0.4602041 , -1.17488761, ...,

In [36]:
a1=np.random.randint(1,100,size=100)
a1

array([43, 49, 94,  8, 14, 44, 77, 47,  6, 69, 67, 56, 75, 13, 61, 10, 67,
       23, 38, 98, 93, 11,  3, 58, 50, 83, 30, 97, 77, 89, 76, 28, 16, 13,
       76,  4, 86, 84, 30,  8, 79, 50, 48, 32, 63, 14,  1, 46, 23, 57, 58,
       84, 86, 22, 67, 23, 14, 84, 78, 60, 34, 31, 63, 10, 15, 80, 84, 99,
       58, 38, 82, 21, 78, 93, 48, 19, 25, 84, 21, 14, 44, 37, 98, 26,  1,
       64, 43, 87, 61, 90, 83, 62,  3, 60, 10, 94, 68, 55, 14, 18])

In [37]:
Z=np.zeros(10)

In [38]:
Z

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [41]:
Z1=np.zeros((10,10))
Z1

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [42]:
Z1=np.random.random((10,10))
Z1

array([[ 0.84868496,  0.04168512,  0.98742333,  0.45238476,  0.82464803,
         0.52318038,  0.68243034,  0.39919808,  0.03892262,  0.19403983],
       [ 0.11975582,  0.70447684,  0.72180031,  0.02454351,  0.72691359,
         0.04404069,  0.14096561,  0.13647466,  0.17505296,  0.44626548],
       [ 0.44584002,  0.03787894,  0.2704143 ,  0.75801553,  0.46908966,
         0.03073102,  0.68878231,  0.96078797,  0.15875611,  0.6996651 ],
       [ 0.58547308,  0.35648707,  0.91286983,  0.12663672,  0.99914835,
         0.28252445,  0.70893593,  0.02630953,  0.55238976,  0.99939406],
       [ 0.79149725,  0.91228618,  0.56243541,  0.50846376,  0.55627459,
         0.08110323,  0.15319952,  0.08050719,  0.54016475,  0.50950566],
       [ 0.65191945,  0.26431033,  0.83954216,  0.03463242,  0.27957516,
         0.04533434,  0.61453578,  0.01985248,  0.42573926,  0.81514428],
       [ 0.08455708,  0.75650705,  0.82020574,  0.57434291,  0.89546672,
         0.38788945,  0.88179713,  0.02104428

In [46]:
Z1=np.random.randint(1,100,size=100)
Z1

array([84,  3,  1, 11,  5,  9, 70, 76, 52, 36, 62, 42, 79, 77, 58, 82, 74,
       82,  3, 86, 83, 40, 52, 60, 21, 68,  5, 41, 67, 45, 54, 95, 61, 95,
       41, 72, 55, 12,  1, 92, 41, 26, 44,  6, 22, 17, 36, 18,  3, 15, 11,
       79, 26, 15, 39, 45, 10, 72, 17, 72,  7, 61, 39, 24, 22, 78, 96, 57,
       65,  3, 92, 17, 92, 63, 44, 19, 64, 96, 16, 21, 79, 96, 37, 30, 19,
       63, 74, 78, 49, 57,  1, 42, 28, 10, 13,  9, 37, 70, 35, 77])

In [47]:
Z1.mean()

45.460000000000001

In [48]:
a1=[1,2,3,4]
a2=[1,2]
a1*a2

TypeError: can't multiply sequence by non-int of type 'list'

In [50]:
A=np.array([[1,2],[3,4]])
Ainv=np.linalg.inv(A)
Ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [51]:
np.diag(A)

array([1, 4])

In [52]:
np.diag([1,2])

array([[1, 0],
       [0, 2]])

In [53]:
a=np.array([1,2])
b=np.array([3,4])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [54]:
np.inner(a,b)

11

In [58]:
X=np.random.randn(100,3)
cov=np.cov(X)
cov

array([[ 0.02101506, -0.11962871, -0.05590364, ...,  0.09978917,
        -0.09799202, -0.15309973],
       [-0.11962871,  0.70600493,  0.27800752, ..., -0.43837799,
         0.58716883,  0.7443138 ],
       [-0.05590364,  0.27800752,  0.21339576, ..., -0.47397319,
         0.21348557,  0.61182599],
       ..., 
       [ 0.09978917, -0.43837799, -0.47397319, ...,  1.14604076,
        -0.31318503, -1.38641026],
       [-0.09799202,  0.58716883,  0.21348557, ..., -0.31318503,
         0.49135936,  0.56466   ],
       [-0.15309973,  0.7443138 ,  0.61182599, ..., -1.38641026,
         0.56466   ,  1.76225962]])

In [59]:
cov.shape

(100, 100)

In [61]:
cov=np.cov(X.T)
cov

array([[ 1.0831287 ,  0.0124236 , -0.02910558],
       [ 0.0124236 ,  0.96444788, -0.04184267],
       [-0.02910558, -0.04184267,  1.22866201]])

In [62]:
np.linalg.eig(cov)

(array([ 1.24109009,  1.07767037,  0.95747812]),
 array([[ 0.19080269,  0.97954507, -0.06392021],
        [ 0.15517503,  0.03419983,  0.98729483],
        [-0.96928584,  0.19829733,  0.14547551]]))